[build-system]
build-backend = "setuptools.build_meta"

requires = [ "setuptools>=61", "wheel" ]

[project]
name = "lasy_incorporation"

description = "Python package for lasy_incorporation"
# Our hand-rolled type-safety infrastructure is getting in the way of 3.14.
# Planning to fix (and remove this again) in the near future:
requires-python = ">=3.10,<3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

dependencies = [
  "matplotlib",
  "numpy>=1.26.2",
  "openpmd-api>=0.16.1",
  "scipy>=1.12",
  "lasy>=0.6.0",
  "tqdm",
]

[tool.setuptools]
packages = [ "lasy_incorporation" ]
